import Navegacion from "@/components/Navigation/Navegacion";
import "./globals.css";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "./registry";
import GlobalProvider from "@/components/GlobalContext";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <StyledComponentsRegistry>
            <Navegacion />
            {children}
          </StyledComponentsRegistry>
          <Footer/>
        </GlobalProvider>
      </body>
    </html>
  );
}
